/**
 * Local test harness for the Read.ai webhook endpoint.
 *
 * Usage:
 *   pnpm test:webhook
 *
 * Prerequisites:
 *   - Local dev server running: pnpm dev
 *   - .env.local populated with WEBHOOK_API_KEY, READ_AI_SIGNING_KEY,
 *     BOT_GITHUB_TOKEN, VAULT_REPO, VAULT_BRANCH, and storage vars
 */
import { createHmac, randomBytes } from 'node:crypto';

// Load .env.local before anything else
process.loadEnvFile('.env.local');

const BASE_URL = process.env.TEST_WEBHOOK_URL ?? 'http://localhost:3000';
const WEBHOOK_API_KEY = process.env.WEBHOOK_API_KEY ?? '';
const SIGNING_KEY = process.env.READ_AI_SIGNING_KEY ?? '';
const BOT_TOKEN = process.env.BOT_GITHUB_TOKEN ?? '';
const VAULT_REPO = process.env.VAULT_REPO ?? '';
const VAULT_BRANCH = process.env.VAULT_BRANCH ?? 'main';
const VAULT_ID = process.argv[2] ?? 'default';

if (!WEBHOOK_API_KEY) throw new Error('WEBHOOK_API_KEY not set in .env.local');
if (!SIGNING_KEY) throw new Error('READ_AI_SIGNING_KEY not set in .env.local');
if (!BOT_TOKEN) throw new Error('BOT_GITHUB_TOKEN not set in .env.local');
if (!VAULT_REPO) throw new Error('VAULT_REPO not set in .env.local');

// Unique IDs per run so dedup never blocks a test
const runId = randomBytes(6).toString('hex');
const REQUEST_ID = `TEST-REQ-${runId}`;
const SESSION_ID = `TEST-SESSION-${runId}`;

const payload = {
  request_id: REQUEST_ID,
  session_id: SESSION_ID,
  title: 'Test Meeting — Webhook Harness',
  trigger: 'meeting_end',
  summary: 'This is a test meeting generated by the local webhook test harness.',
  start_time: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  end_time: new Date().toISOString(),
  participants: [
    { name: 'Alice Test', first_name: 'Alice', last_name: 'Test', email: 'alice@example.com' },
    { name: 'Bob Test', first_name: 'Bob', last_name: 'Test', email: null },
  ],
  owner: { name: 'Alice Test', first_name: 'Alice', last_name: 'Test', email: 'alice@example.com' },
  action_items: [{ text: 'Follow up on test item' }],
  key_questions: [{ text: 'Did the webhook work?' }],
  topics: [{ text: 'Integration testing' }],
  report_url: 'https://app.read.ai/analytics/meetings/TEST',
  chapter_summaries: [
    {
      title: 'Test Chapter',
      description: 'Testing the webhook pipeline end to end.',
      topics: [{ text: 'Integration testing' }],
    },
  ],
  platform: 'zoom',
  platform_meeting_id: `test-${runId}`,
};

function sign(body: string): string {
  const keyBuffer = Buffer.from(SIGNING_KEY, 'base64');
  return createHmac('sha256', keyBuffer).update(body).digest('hex');
}

async function sendWebhook(): Promise<void> {
  const body = JSON.stringify(payload);
  const signature = sign(body);
  const url = `${BASE_URL}/api/webhooks/${WEBHOOK_API_KEY}/${VAULT_ID}/readai`;

  console.log(`\n→ POST ${url}`);
  console.log(`  request_id : ${REQUEST_ID}`);
  console.log(`  session_id : ${SESSION_ID}`);
  console.log(`  expected   : meetings/${SESSION_ID}.md in ${VAULT_REPO}@${VAULT_BRANCH}\n`);

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-read-signature': signature,
    },
    body,
  });

  const text = await res.text();
  let json: unknown;
  try {
    json = JSON.parse(text);
  } catch {
    json = text;
  }
  console.log(`← ${res.status}`, json);

  if (!res.ok) {
    console.error('Webhook returned non-2xx — aborting git check.');
    process.exit(1);
  }

  if ((json as { duplicate?: boolean }).duplicate) {
    console.warn('Marked as duplicate — this request_id was already processed.');
    process.exit(0);
  }
}

async function checkGitHub(retries = 8, delayMs = 3000): Promise<void> {
  const path = `meetings/${SESSION_ID}.md`;
  const apiUrl = `https://api.github.com/repos/${VAULT_REPO}/contents/${path}?ref=${VAULT_BRANCH}`;

  console.log(`\nWaiting for git commit (up to ${retries} retries × ${delayMs / 1000}s)…`);

  for (let attempt = 1; attempt <= retries; attempt++) {
    await new Promise((r) => setTimeout(r, delayMs));

    const res = await fetch(apiUrl, {
      headers: {
        Authorization: `Bearer ${BOT_TOKEN}`,
        Accept: 'application/vnd.github.v3+json',
      },
    });

    if (res.ok) {
      const data = await res.json() as { sha: string; html_url: string };
      console.log(`\n✓ Committed! (attempt ${attempt})`);
      console.log(`  sha      : ${data.sha}`);
      console.log(`  view at  : ${data.html_url}\n`);
      return;
    }

    console.log(`  attempt ${attempt}/${retries}: ${res.status} — not yet`);
  }

  console.error(`\n✗ File not found in git after ${retries} attempts.`);
  console.error(`  Checked: ${apiUrl}`);
  process.exit(1);
}

(async () => {
  await sendWebhook();
  await checkGitHub();
})();
